### ISSUE TITLE
Avoid unknown fishing:sandy nodes

### ISSUE THREAD

**Issue by jhcole** [FozLand/fishing#2]
fishing:sandy should be converted to default:sand

**Comment by mootpoint** [comment]
We talked about converting Sandy into sand

**Comment by mootpoint** [comment]
added code, please test on development environment. I will then close issue.

**Comment by mootpoint** [comment]
Tested on personal server. Will eliminate unknown blocks in world. if there is a way to gracefully handle unknown items in player's inventory please feel free to reopen issue :) until then... Done
